### ISSUE TITLE
Does the "Fix jerky movement" option work currently?

### ISSUE THREAD

**Issue by vanfanel** [sulix/omnispeak#17]
Hi there!

I have just built omnispeak for the first time. Since those EGA games must have been tied to a 70Hz display mode back in the day, I am not surprised that the timing in this engine tries to replicate that (I guess original games ran at 35FPS, since thats an exact divisor for 70. At least Keen 1 did, so...)

However, I see you have a "Fix jerky movement" option which is very promising, since it could let the game run in uncapped FPS mode, where the only speed limit would be SDL2 vsync in SDL2_RenderPresent(). Well, this option does not do anything, and looking at the game logic I fail to see what code does it affect.
So, is it a "dummy" option for now, to be implemented in the future?

NOTE: The game video thread should simply rely on SDL2_RenderPresent() vsync to have a smooth movement, never use internal SDL_Delay() or similar stuff internally. Thats good for game logic if it goes in its own thread, but not for video if you want to get smoot movement synced to physical screen mode.

**Comment by sulix** [comment]
Thanks for trying Omnispeak. It looks like there are a few different questions here: I'll try to cover them all, but let me know if I've missed anything.

The "Fix jerky motion" option doesn't do anything at present. It's actually supposed to be a workaround for some EGA/VGA cards which need the vblank detection to work slightly differently. In this sense, it's really only relevant to the (still unfinished) DOS port of omnispeak. It would potentially be possible to re-use the option for something like VSync on non-DOS platforms, though, which I guess is what you're suggesting. My suspicion would be that it'd be worth making a separate option for VSync if we add that, though, as it'd also be relevant in DOS, which has other uses for the "Fix jerky motion" setting.

As you suspected, Keen 4–6 run at a maximum framerate of 35Hz. The game does not totally decouple the rendering from the game update: some of the physics, for example, is calculated once per frame, and there are some bugs when running at > 35Hz. For example, it becomes very difficult to do "ledge-grabbing" at 70Hz. Since we're trying to preserve perfect compatibility, we don't intend to fix any of these issues. The in-game timer runs at 70Hz, so it's not possible for the game to update faster than that without actually speeding up gameplay. And even if the renderering were fully decoupled from the update, there's no point rendering the same frame twice if nothing has updates. It's also worth noting that the game will run at ~23Hz while playing back demos (with the variable framerate support disabled), in order to maintain synchronisation even on older machines.

(If you do want to try the game at 70Hz — which is noticeably smoother, if buggier — you can chage the "2" to a "1" here: https://github.com/sulix/omnispeak/blob/master/src/id_rf.c#L1009 )

As for VSync, currently, we don't explicitly enable VSync on any of the graphics backends. If you're using the SDL2 render backend (make RENDERER=sdl2), we do use SDL_RenderPresent(), and you can use the SDL_RENDER_VSYNC environment variable to force enable it or disable it. Again, the framerate will be limited to a maximum of 35Hz ingame, but it will be quite playable even with a display framerate that's not a perfect multiple of 35. If we wanted to sync perfectly to 60Hz or similar, though, we would need to slow the game down a bit (if you're curious and want to experiment, the timing code is actually largely in the sound system in id_sd*, as that's how the original game did it).

Hopefully that answers your questions. Unfortunately, as we're pretty constrained to how the original game operated, there isn't a useful way to "unlock" the framerate beyond what the original game did. I'm more than happy to answer any further questions you might have though.

**Comment by vanfanel** [comment]
Thanks for your response, sulix!

Well, what I meant with "unlocked framerate" was more like "let the game run at vsync rate", so it could run at ~60FPS on most systems, as in modern screens the physical refresh rate is ~60Hz. That would allow smooth scrolling, since scrolling at 35FPS on a ~60Hz display does not look very good, and its a pity because those Keen games are great other than that.
Would 60Hz also break physics? Maybe phisics could be tweaked to work at near-60FPS speeds? OR at least ~30FPS, since 30FPS is an exact divisor of 60 and then the games would look smooth on a near-60Hz display...

**Comment by owenmpierce** [comment]
The game originally ran ticks at 70Hz.  Ideally, each game loop would take two tics so that you would get drawing and physics at 35Hz, but the creature behaviours and the physics were written to be scaled by a delta-time variable (called "tics" in wolf3d, catacomb, and probably the original keen source code) so that the game could run at lower framerates.  I think that the lowest framerate allowed would have been 70/6 Hz =~ 11 Hz, because MAXTICS was #defined as 6 in keen.  

You can see how it works in catacombs 3d, which is essentially the same as in keen. https://github.com/historicalsource/catacomb3d/blob/master/ID_RF.C.  Or you can download my CK Source Mod and poke around (ctrl+F for RFL_CalcTics). https://keenmodding.org/viewtopic.php?f=13&t=1926.  You can also see that demos are locked at a fixed framerate which is required for a repeatable simulation.

There are a few options The simple way to adjust the framerate would simply be to run tics at 60 Hz so that the game loop updates at 30 Hz.  This wouldn't alter the physics, but it would make the game run at 6/7ths speed.  

Another way would be to change this 2 to a 1 https://github.com/sulix/omnispeak/blob/master/src/id_rf.c#L1009 so that each game loop only takes one tic. This would be like modifying MINTICS in the original game (which I have tried in my source mod).  Then you will have 70 Hz physics, which will be very different and worse.  

The correct way to do it would be to run the physics at the usual rate of 35 Hz, but to draw at unlimited frequency and to interpolate the camera coordinates and the position of each sprite before each frame draw.

**Comment by sulix** [comment]
FYI: in the latest builds, it's now possible to run Omnispeak at 60FPS, though I'd strongly recommend against it.

To do so, you'll need to add the following to OMNISPK.CFG:
```
rf_minTics = 1
sd_sfxPartRate = 120
```

This will effecively give you the "70Hz" physics mentioned above (which are very smooth, but make some things behave weirdly, and aren't recommended). It'll then just slow the entire game down to 6/7ths (~86%) of its original speed: even the music will play more slowly. Think of it like playing a bad PAL conversion of an NTSC game where everything runs more slowly. :)

You could equally run the game at 30 FPS with the original physics by just using the ``sd_sfxPartRate`` line, or at 70 Hz by just using the ``rf_minTics`` line.

Also, note that the game still will use its own timer, not VSync for timing with these options enabled. You can now enable VSync in Omnispeak, either through the menu or by adding ``swapInterval = true`` to OMNISPK.CFG, but it's not used for game timing, just to prevent tearing, so there may occasionally be a hitch if the game timer doesn't perfectly match the monitor's.

This is as close as I think we'll get to the dream of a 60 Hz Keen without a lot of work, so I'm going to close this issue now. I think projects like [Commander Genius](https://clonekeenplus.sourceforge.io/) have their own, more framerate-independent physics, so are better suited to this if physics is going to differ anyway.

**Comment by sulix** [comment]
Just as a quick update here, the DOS version now takes the "Fix Jerky Motion" config option into account, as of c48cb63e91bae77a3d369b47e29a035dff359413.

It currently uses [K1n9_Duk3's modified VBlank implementation](https://pckf.com/viewtopic.php?t=6192), so it doesn't exactly match the original game, but should be more compatible with DOSBox. Nevertheless, you should keep "Fix Jerky Motion" off in the DOS version unless you have one of the specific machines which require it. The only machines I'm aware of which require it are:
- Texas Instruments TravelMate 4000E 486 WinSX/25MHz Color
- Any Vortex86VGA mini-PCIe VGA cards, used with, e.g., the 86duino.

**Comment by cathoderaydude** [comment]
Hey @sulix, I don't know if it's rude to necro an issue like this to just ask a question out of curiosity, please forgive me if so. I'm confused by all the references to 70hz / 35hz, and trying to figure out what I'm missing.

As I understand it, games designed natively for VGA cards (like Doom) ran at 35fps because it's half the 70hz refresh rate of VGAs 320x200x8bpp mode (13h.) But actual EGA was only 60hz in all modes, and as far as I know the Keens ran in EGA's 320x200x4bpp (mode Dh.) Shouldn't that mode still only render at 60hz, even on a VGA card?

**Comment by sulix** [comment]
No worries about bringing this issue up again (and I'm a fan of your videos, so thanks!)

You'd think so, but no — all 400-line modes (which, due to line doubling, includes 320×200) run at ~70Hz on VGA. There's no difference in the timings between 13h and 0Dh, just the way the pixel data is generated. VGA does use 60Hz for the 480-line modes. That being said, there are some VGA setups which do use 320×200@60Hz — laptops (and the Hand386) often had a mode which ran at 60Hz to better cope with LCDs.

Yes, this is a change in behaviour from EGA, but I guess refresh rate just wasn't seen as being that important, particularly for IBM's more business-focused customers. And graphics code didn't tend to hardcode the refresh rate, but just checked the appropriate registers to see if vblank was happening.

Commander Keen was coded entirely on VGA machines (as EGA was on its way out anyway), so 70Hz must have seemed more natural as a base tic rate. EGA cards were likely on older machines anyway, so might not have been able to maintain 30/35 fps consistently, so it probably wasn't as much of an issue.

On 60Hz modes, Keen will stutter a bit, as the game will render at 30Hz, but occasionally fit an extra update in so that the game runs at the normal 70Hz speed on average. This is because (as mentioned above), the actual game timing code comes from the sound system.

There was good thread on [PCKF](https://pckf.com/viewtopic.php?t=16773) and [Vogons](https://www.vogons.org/viewtopic.php?f=63&t=96028) recently which discusses this in excruciating detail, and also has a [modified version of Keen](https://github.com/juj/KEEN70HZ) which both removes the 2-frame (35Hz) limit, and makes the game timing run off the actual VGA timings, not the PIT (which can prevent rare stutters if the timings don't perfectly match up).

Hope that helps!

**Comment by cathoderaydude** [comment]
That helps _tremendously_, and it's funny that you know my channel because now it'll make sense when I say: this is probably gonna keep me from making an ass of myself in some future video, hah.

This is fascinating stuff and I'll make sure to read the thread you linked, but you've already answered the question I was driving at before I had a chance to ask it - I somehow missed what you said earlier about the timing in the sound code, I see it now, so at worst we're just talking about a little visual judder, no physics impact. Cool!

That said (and I'll stop pontificating here for the sake of anyone who's CCed) it sounds like any earlier games written for actual-EGA cards, that might have relied on vblank for timing, would run 16% faster if played on a VGA card, assuming no CPU bottleneck. I wonder how many games that broke, and if IBM noticed or cared or offered any solutions.

Thank you so much! Great work on this project btw!
