### ISSUE TITLE
port to retrofw video glitches

### ISSUE THREAD

**Issue by Poligraf** [sulix/omnispeak#25]
I am trying to port omnispeak to the retrofw line of devices.

This is a linux based portable handheld running a MIPS jz4760 processesor.

It uses SDL1 and I am using mipsel-linux-gcc 7.3.0. No issues were present when building this natively for x86 linux using SDL1.

The same build flags are causing very odd video glitches when you are backtracking on the handheld device. 

Exactly half the screen becomes glitched. Going into the start menu or going forward fixes the issue.

Screen resolution of device is 320x200, but has an IPU so it can downscale any resolution from 800x600 and below to fit the screen.

Thank you in advance for your responses

![error screen](https://user-images.githubusercontent.com/2182279/96334538-0cdc3e80-10ce-11eb-9e9a-94bf10c2f233.jpg)

**Comment by sulix** [comment]
Hmm…. that's really odd. I admit the SDL1 backend isn't as well tested as the SDL2 / OpenGL ones, but even so, I can't think of anything that could cause that sort of glitch.

One thing that might be worth trying is to uncomment "#define ALWAYS_REDRAW" in ck_config.h — this may slow the game down a bit, but could get rid of some glitches. This basically makes the game redraw the entire screen every frame, rather than only trying to redraw things that have changed.

Otherwise, I can't think of anything that could cause that particular sort of corruption — it's pretty weird, affecting random parts of the screen — but I'll have a bit of a look at the SDL1 backend over the weekend and see if anything crops up.

**Comment by Poligraf** [comment]
Wow, thank you for quick reply. 
This has not fixed the issue which is odd.
It does not affect random parts of the screen only the left half. This only happens when you go backwards. 
I only tested with Keen 4 demo and  Keen 4 v1.4 EGA.

**Comment by sulix** [comment]
Okay: I have a couple of ideas.

1. Turns out there's a bug in VL_SDL12_SurfaceToSurface() (in ``id_vl_sdl12.c``): both ``surf`` and ``dest`` should be locked before the memcpy() loop, and unlocked afterwards. I'll commit a fix to this soon: it doesn't seem to affect X11 on my x86 machine, but maybe other backends require it.
2. The next function, VL_SDL12_SurfaceToSelf() is used for scrolling the tile buffer. I think this one should work across all architectures, as it's pretty careful to use memmove() to support overlapping regions, but it's possible there's a bug I haven't noticed.
3. It may also be worth looking at RFL_NewRowVert() in ``id_rf.c``: this is the code which draws the new strip of tiles along the side when scrolling. Again, I think this shouldn't be buggy, but maybe.
4. Otherwise, look at RF_SmoothScroll() and VL_SDL12_ScrollSurface() — they handle most of the rest of the scrolling.

A couple of questions for you:
1. When you say this only happens when you go backwards, does that mean when scrolling to the right? To the left? Or both, depending on where you've been?
2. What Keen 4 demo did you try with — Omnispeak shouldn't support the Keen 4 demo, just v1.4 EGA?

**Comment by Poligraf** [comment]
Thank you for the commit,you have been extremely helpful - but this did not fix the issue :(

I do not want to go on a wild goose chase with this old and slow portable device as it is hard to recreate, so I will close this ticket in the next 24 hours so I do not waste your time.

1) I have verified that this only happens when you are scrolling to the right but not the left.
2) The Keen 4 demo I tried with was the one that came with your linux binary.

I have since tried it with Keen 5 1.4 EGA and I have verified this happens on Keen 5 as well.

**Comment by Poligraf** [comment]
If you have any good ideas I am keen to hear them, but I do not want for you to waste your time on SDL1 on

**Comment by sulix** [comment]
I'm afraid I don't have any brilliant ideas. Do the sprites (keen, enemies, etc) get corrupted as well, or just the tiles (backgrounds, level geometry)? They can get scrolled somewhat differently.

What I have done — which might help with debugging — is written a new SDL 1.2 backend. This one is based on the OpenGL backend, and does all of its own rendering in software, just using SDL to display the final frame to the screen. If that's broken as well, then we can know that the problem is in the VL_SDL12_Present() function, or in something in SDL or the system libraries, in which case there's probably not much we can do to fix it.

The replacement SDL 1.2 backend is here:
https://davidgow.net/stuff/id_vl_sdl12hack.c

Just replace ``id_vl_sdl12.c`` with it — or better yet, change the reference to ``id_vl_sdl12.o`` to ``id_vl_sdl12hack.o`` in the Makefile to build with it instead. I haven't tested it much, but it shares very little code with the other SDL 1.2 backend, so should have some small chance of working.

All the best
— David

**Comment by Poligraf** [comment]
Wow thank you for help but this also did not fix the issue. Sorry :(
Keen and enemies are not corrupted only backgrounds and level geometry and only when scrolling from left to right. (Keen is going right).

I am only changing the compiler in the makefile
`DEFAULT_STATIC = 0
DEFAULT_RENDERER = sdl1
DEFAULT_BUILDASCPP = 0
DEFAULT_LOCAL_SDL = 0
BINDIR =
LIBGL = -lGL
LIBVULKAN = -lvulkan
OUTDIR_SUFFIX := INVALID`

`CXX = mipsel-linux-g++
CC = mipsel-linux-gcc`

**Comment by sulix** [comment]
Hmm… it's definitely odd. I fear there's probably not much more to try.

I have reuploaded the ``id_vl_sdl12hack.c`` [fire here]( https://davidgow.net/stuff/id_vl_sdl12hack.c) with a rewritten VL_SDL12HACK_SurfaceToSelf() function, which avoids calling the memmove() function. That'd fix the case where memmove() is buggy (which would indeed show up as scrolling breaking only in one horizontal direction). If memmove() doesn't work, though, that's something pretty fundamentally wrong with the environment.

**Comment by Poligraf** [comment]
The latest file works. No issues. This is great :+1:

**Comment by sulix** [comment]
Glad to hear that worked.

It looks like the ``memmove()`` function is broken in that retrofw build, then… Do you know what libc / libc version it uses? The "proper" solution is probably to fix that, rather than working around it in Omnispeak.

Nevertheless, I've [updated](https://github.com/sulix/omnispeak/commit/d71777e05d1ec361f1f55ffab05a8ef1359d805a) the Omnispeak SDL1.2 backend to avoid memmove(). This is a change to the original SDL1.2 backend, not the hacky one I wrote above, so it's probably worth testing it independently to see if this actually fixes it for good.

**Comment by Poligraf** [comment]
Hi David

I am sorry if the statement below seems confusing as I am far from an expert on these topics.

1) I am using `uClibc-ng-1.0.28`
2) `memmove()` is used extensively in different places in retrofw ports. In fact `memmove()` is preferred than `memcpy()` on this device due to speed. It is used extensively in the pocketsnes port for example here https://github.com/retrofw/pocketsnes/blob/master/sal/sal_common.c#L713

Not sure what to do next as far as the bug is concerned. I spoke to the maintainers of retrofw https://github.com/retrofw/retrofw.github.io (who are very active) and I will log a retrofw ticket as we would like to get to the bottom of this. 

The only thing I would ask if you could check the values in `sw` as pingflood alluded that this also might be the cause of the issue, but it is acknowledged that it is equally likely that there is something wrong on the retrofw side.

**Comment by sulix** [comment]
Aha! I think I may have found this.

It turns out that this is a [known](https://mailman.uclibc-ng.org/pipermail/devel/2016-April/000837.html) [bug](https://mailman.uclibc-ng.org/pipermail/devel/2018-March/001648.html) in the uClibc-ng ``memmove()`` implementation on MIPS systems, when called with overlapping regions (as Omnispeak does).

The good news is that it has been [fixed](https://cgit.uclibc-ng.org/cgi/cgit/uclibc-ng.git/commit/?id=785dee78552f9ad06819bf7eb1adc05b43110842) [upstream](https://cgit.uclibc-ng.org/cgi/cgit/uclibc-ng.git/commit?id=e94e6f4bd91c92c7e1cc21d82ed9320dd722add2), but alas after version 1.0.28.

Version 1.0.32 or later of uClibc-ng should include the fix.

(As an aside, I'm suspicious of ``memmove()`` being faster than ``memcpy()`` — if that's really the case, why doesn't memcpy() just call memmove()? Maybe it's faster because it was broken? But even then, it seemed like it used to call memcpy()…)
