### ISSUE TITLE
Keen 6 eyeball platform camera bug missing

### ISSUE THREAD

**Issue by tgies** [sulix/omnispeak#27]
Hi, thanks for your great work on this reimplementation. Recently I got curious about the root causes of some of the well-known bugs in Keen Galaxy (Keen 5 door wrong warp, Korath fuse, Impossible Bullet, etc.) and started reverse engineering them. I was pleased to find that Omnispeak faithfully copied the logic behind these bugs and it was a great help in understanding them.

However, I identified one bug from the original games which does not occur in Omnispeak for whatever reason: the Keen 6 eyeball platform camera bug. This can be seen [`here on YouTube`](https://www.youtube.com/watch?v=AjXVBz_-8TY) and the steps to reproduce are as follows (I am pretty sure this should work in all versions of Keen 6, but definitely in 1.4):

1. Enter the final Bloog Control Center level of Keen 6
2. Stand on one of the eyeball platforms that hang from the ceiling in some of the last few rooms of the level.
3. Save the game.
4. Load the game. The camera will be showing an entirely different area of the level and will not correctly track Keen until he resets the camera by going through a door.

In Omnispeak, the camera just continues behaving correctly when I try to trigger this bug. My guess is that there is some slightly different platform collision logic triggering this bug in Keen 6 that is missing from Omnispeak but I haven't gotten far enough into disassembling Keen 6 to say.

Do you know why this bug is missing from Omnispeak, or would it be helpful for me to try to trace out the logic in the original Keen 6 EXE and share my findings?

**Comment by sulix** [comment]
Thanks for reporting this — I'm away at the moment and won't be able to look into it for a couple of days, but here are some initial thoughts.Given this bug involves saving/reloading, could you try saving with keen, then loading that save with omnispeak and vice-versa? That should help track down of the issue is before or after that point.If the problem is on the loading side, one other possibility of to try using the playloop dumper feature to see if there's any differences in the object state.Regardless, I'll try to have a look at this when I get back.

**Comment by tgies** [comment]
Well, I quickly ran into problems interchanging savegames only to realize that I was reproducing this bug in Keen 6 1.0, not 1.4, and it was simply fixed in 1.4. So it is probably just out of scope for Omnispeak. Whoops. Thanks for your response anyway!
