### ISSUE TITLE
CI build from 7cb5bb32c6b09e7d50ac170a0fc7b089b40ad46f is broken on Win10

### ISSUE THREAD

**Issue by mankeli** [sulix/omnispeak#39]
I'm using Keen4 (v1.4) that works with the 1.0 version downloadable from the page. I tried to use a newer build from the CI. So I copied the datafiles from my older Omnispeak dir, got https://github.com/sulix/omnispeak/actions/runs/1162760365 "Windows Build" and neither of the exes (32/64) do anything. (running the exes just quits without message)

Then I tried https://github.com/sulix/omnispeak/actions/runs/1162760374 - "Windows Build (mingw-x86_64-RelWithDebInfo) " also quits without a message. "Windows Build (MSVC-x64-RelWithDebInfo)" Runs the keen4 up to title screen, but then crashes. Looking at it on MSVC debugger reveals it crashes with callstack  CAL_HuffExpand/CA_CacheAudioChunk/CA_LoadAllSounds

I understand the CI builds are unstable, but since there isn't any tags for releases, I don't know which version I should use.

**Comment by mankeli** [comment]
Okay, just after posting this I tried to download the keen 1.4 that's mentioned in the readme, and that worked, so apparently the copied data from the older omnispeak was the culprit.

**Comment by sulix** [comment]
Thanks for reporting this, and I'm glad you got it working!

Would you mind letting me know exactly what combination of data files were causing the problem?  While it's true that the older data could cause a problem, I'd've expected you to at least get an error message (and that's what seems to happen if I run those builds myself, under wine or Win10).

If I just copy the .exe over, I get an error message (both a dialogue box and a message printed to the command line):
```
GetFunction: Could not find function "CK4_HatchEgg"
GetFunction: Function not found. Check your 'ACTION.CKx' file!
```
But using the newer ACTION.CK4 does fix it.

For the CMake-based builds (from the 2nd link), I also need to copy over the 64-bit SDL2.dll.

With both of those, the game works perfectly — even if the other files are older.

These sorts of errors are what I'd've expected from using the data files included with the "Omnispeak 1.0" download with a newer executable. The only cause I can think of of, for example, the ``CAL_HuffExpand``, etc, issues would be if the ``AUDIOHHD.CK4``, ``AUDIODCT.CK4`` and ``AUDIO.CK4`` files don't match, but those haven't changed since I released version 1.0. (Alternatively, it could be a bad struct alignment, but I think we fixed all of those.)

Were you using version 1.0 of Keen 4 (as opposed to 1.0 of Omnispeak)? Omnispeak only supports version 1.4 of Keen 4…

In any case, thanks a lot. I'm planning to do another proper release of Omnispeak this year, which should mean there are more convenient downloads for newer versions then.

**Comment by mankeli** [comment]
1.4 version of Keen4, 1.0 of Omnispeak. I can check later if I still have the files.

I added the 64bit SDL2.dll (from libsdl.org) manually when it was missing from the build artifacts. But yeah no error dialogs or console messages anywhere here. Just silent quit on the MinGW builds and crash with MSVC build. (probably would be "application stopped working" dialog if I wouldn't have msvc installed)

**Comment by sulix** [comment]
Weird…

I definitely can't reproduce any of that here, though I'm mostly a Linux person, so it's definitely possible there's something I'm missing. Maybe an anti-virus program or something being tripped up on mingw builds (it has been known to happen)? Even then, that wouldn't explain everything.

If you've got the exact files that broke, I can try to reproduce it again here with them, but I'm starting to think this is at least partially system-specific in some way. In any case, at least it's working now. But maybe I'll use the MSVC build for windows when I do the next release just in case…

**Comment by mankeli** [comment]
I sent some test cases into your email. I think I tested keen6 with a different version, but it seems that the behavior is similar so I hope they are useful to you!

**Comment by sulix** [comment]
Thanks. Both of the cases are crashes in the Huffman decompressor, and appear to be caused by some corrupted/invalid/incorrect files.

In Keen 4:
- ``AUDIO.CK4`` doesn't match any version I'm aware of. All versions of Keen 4 have the exact same ``AUDIO.CK4``, which doesn't match this one.
- ``AUDIOHED.CK4`` also doesn't match. This shouldn't matter, as Omnispeak now uses ``AUDIOHHD.CK4`` as the filename for this, and the version you sent is correct.

In Keen 6:
- ``EGAGRAPH.CK6`` doesn't match either of the supported versions. It's from Keen 6 EGA 1.0, and Omnispeak only supports Keen 6 EGA 1.4 or 1.5.
- ``GAMEMAPS.CK6`` likewise.

Ideally, there'd be some better handling of these cases, rather than attempting to load the data and crashing (which, to be fair, is what would happen in the original DOS versions), but there's only so much we can do given there's not much error handling in the original.

Thanks for digging into this anyway!
