### ISSUE TITLE
Crash in Keen 5's Gravitational Damping Hub (Level 11)

### ISSUE THREAD

**Issue by snelson7220** [sulix/omnispeak#42]
In level 11 of Keen 5, the game may crash and exit when jumping to collect the vitalins pictured in the first screenshot.

Steps to reproduce the crash:
1. Load Keen 5 and enter level 11 via world map, F10+W cheat, or save file (I have attached a save file for quick testing for this crash)
2. Reach the area around the middle of the map with the vitalins hovering near a switch that opens up a platform causing Keen to drop below
3. Walk right and jump to collect the vitalins
4. Omnispeak crashes, but only occasionally. It has a 50/50 chance of crashing while grabbing the items, the error message in question reads "RF_AddSpriteDraw: No free spots in spritearray"

Tested with the latest Windows artifacts (both 32bit and 64bit) and the 1.0 version hosted on David Gow's website, although the 1.0 version does not display the above error message and instead quits unexpectedly.

![crash1](https://user-images.githubusercontent.com/67773366/135912890-af6acbfe-e731-4d83-9e10-e30b046c60c6.png)
![crash2](https://user-images.githubusercontent.com/67773366/135912898-2451accd-5b72-4c9b-820d-a25b5144035f.png)

[SAVEGAM5.zip](https://github.com/sulix/omnispeak/files/7280734/SAVEGAM5.zip)

**Comment by sulix** [comment]
Thanks very much for the detailed report.

It turned out that Omnispeak actually only allowed 48 onscreen sprites, whereas Keen 5 had room for 60. I've updated it, and future versions should work properly in the Gravitational Damping Hub (and, indeed, everywhere). I'm surprised that so much of the game worked properly with the lower limit, actually.

The older 1.0 version didn't use messageboxes to display error messages: it was giving the same error, but just printing it to the command line.

You should be able to download a fixed version from here:
https://github.com/sulix/omnispeak/actions/runs/1307470406

Thanks a bunch, and Happy Keening!
— David

**Comment by snelson7220** [comment]
Just tested the new version and it works perfect, thanks for addressing that! In the previous version I encountered a similar crash once in Keen 4 after loading a save, but wasn't able to reproduce the crash until I reached this area in 5, so I suppose it was possible to trigger it elsewhere but difficult to do so.
