### ISSUE TITLE
Starting omnispeak shows a window with text "MM_GetPtr: Out of Memory!", then exits

### ISSUE THREAD

**Issue by synthead** [sulix/omnispeak#44]
When I start omnispeak, I get this window:

![image](https://user-images.githubusercontent.com/820984/174036162-099ad062-7238-464f-ae95-7cfaf09ec5ca.png)

This is what's written to the CLI:

```
$ omnispeak /gamepath /usr/share/omnispeak/keen4
Parsed 0 config options from "OMNISPK.CFG" over 0 lines
Warning: MM_GetPtr: Failed to alloc block (-1273300583 bytes) with system malloc. Trying to free some space.
MM_GetPtr: Out of Memory!
```

I built v1.1 from sources from https://github.com/sulix/omnispeak/releases/tag/v1.1.  Here's a little information about my system:

- Arch Linux
- glibc 2.35-6
- make 4.3-3
- gcc 12.1.0-2
- cmake 3.23.2-1

Here's how I compiled it:

```
cmake -B build -S omnispeak-1.1
KEENPATH=/usr/share/omnispeak XDGUSERPATH=1 cmake --build build
```

I have copied the data/ directory in the archive to `/usr/share/omnispeak/keen4`, and acquired `AUDIO.CK4`, `EGAGRAPH.CK4`, and `GAMEMAPS.CK4` from [archive.org](https://archive.org/details/msdos_Commander_Keen_4_-_Secret_of_the_Oracle_1991) (which is also in `keen4/`).

**Comment by sulix** [comment]
Thanks for checking out Omnispeak!

It looks like the problem is that the version of Keen 4 on archive.org is v1.0, and Omnispeak requires v1.4.

There's an official download of version 1.4 from Apogee/3D Realms, though it's annoyingly still on an FTP server, and I think comes bundled with an installer: ftp://ftp.3drealms.com/share/4keen.zip

Otherwise, I keep a copy of the shareware version, with all the necessary files accessible here: https://davidgow.net/keen/4keen14.zip

This also should match the version sold as part of the Steam and GOG downloads, as well as the old 3D Realms/Apogee downloads.

Debian's game-data-packager also has some details on the supported versions:
https://salsa.debian.org/games-team/game-data-packager/-/blob/master/data/keen.yaml

That being said, I definitely should improve the error message in this case. I'd wanted to let Omnispeak try to load unknown versions in case people wanted to try mods and level packs, but failures in memory allocation are pretty user-unfriendly.

**Comment by synthead** [comment]
Heya @sulix, thanks for the quick response!

I attempted the three game files from the `4keen14.zip` file, and it started and ran just fine!  Seems like it was just a binary version mismatch, after all.

> That being said, I definitely should improve the error message in this case. I'd wanted to let Omnispeak try to load unknown versions in case people wanted to try mods and level packs, but failures in memory allocation are pretty user-unfriendly.

Seconded!  Perhaps a little md5sum check could be built in to determine if the game data is correct?  If not, you could display a window that shows which files were rejected and why :+1:

**Comment by synthead** [comment]
This specific issue is a-ok on my end now, so I'm closing this issue.  Thanks for the help!

I also created this issue to help improve the error message, just like you described: https://github.com/sulix/omnispeak/issues/45
